// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwo8nyYxSJ207Asf8_M4HNHQ--w6KrnI',
    appId: '1:633683696026:web:f262742fe179f3b734c223',
    messagingSenderId: '633683696026',
    projectId: 'remind-me-5c94b',
    authDomain: 'remind-me-5c94b.firebaseapp.com',
    storageBucket: 'remind-me-5c94b.appspot.com',
    measurementId: 'G-G5NX7T57DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NW778REh7RnefWj8MteOLyP5V_kE9FA',
    appId: '1:633683696026:android:18915536a6f0550834c223',
    messagingSenderId: '633683696026',
    projectId: 'remind-me-5c94b',
    storageBucket: 'remind-me-5c94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBstvGbKV_XnvmKdnC1zogSBlCQHY1fC8M',
    appId: '1:633683696026:ios:a6621237bc65da5334c223',
    messagingSenderId: '633683696026',
    projectId: 'remind-me-5c94b',
    storageBucket: 'remind-me-5c94b.appspot.com',
    iosClientId: '633683696026-osfhdstqtm24aem875vpblv181eo1fts.apps.googleusercontent.com',
    iosBundleId: 'io.param.remind.remindMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBstvGbKV_XnvmKdnC1zogSBlCQHY1fC8M',
    appId: '1:633683696026:ios:a6621237bc65da5334c223',
    messagingSenderId: '633683696026',
    projectId: 'remind-me-5c94b',
    storageBucket: 'remind-me-5c94b.appspot.com',
    iosClientId: '633683696026-osfhdstqtm24aem875vpblv181eo1fts.apps.googleusercontent.com',
    iosBundleId: 'io.param.remind.remindMe',
  );
}
