name: first
on: [push, pull_request] 

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Run gradle task
      uses: jojo243/android-gradle-action@2.1.3
            
      
