name: first
on: [push, pull_request] 

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Current Date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Current Date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Current Date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    
    
  
